name: games_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  slide_countdown: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  fonts:
    - family: Outfit
      fonts:
       - asset: assets/fonts/Outfit-Regular.ttf
    - family: Cairo
      fonts:
         - asset:  assets/fonts/Cairo-VariableFont_slnt,wght.ttf    
  uses-material-design: true
  assets:
    - assets/lang/